spring:
  application:
    name: gateway-server

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/eureka/
zuul:
  routes:
    trade-server:
      serviceId: trade-server
      path: /trade/**
    login-server:
      serviceId: login-server
      path: /user/**