spring:
  application:
    name: gateway-server

server:
  port: 8084
  servlet:
    context-path: /gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/eureka/

zuul:
  routes:
    login-server: /user/**
    trade-server: /trade/**