spring:
  application:
    name: login-server
  datasource:
    url: jdbc:mysql://localhost:3306/wt_sjw?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/eureka/

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug


